skip_tags: true
clone_depth: 1

os: Visual Studio 2015

environment:
   matrix:
      - PYTHON_VERSION: 2.6
        MINICONDA: C:\Miniconda
      - PYTHON_VERSION: 2.7
        MINICONDA: C:\Miniconda
      - PYTHON_VERSION: 3.3
        MINICONDA: C:\Miniconda3
      - PYTHON_VERSION: 3.4
        MINICONDA: C:\Miniconda3
      - PYTHON_VERSION: 3.5
        MINICONDA: C:\Miniconda3

platform:
   - x86
   - x64

build_script:
   - uname -a
   - df -h
   - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   - conda info -a
   # Build into own Conda test environment in
   # order to control the build environment
   - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
   - activate test-environment

test_script:
   - nosetests
